### ISSUE TITLE
IMKClient and IMKInputSession bug on macOS Sequoia

### ISSUE THREAD

**Issue by nickmcintyre** [processing/processing4#864]
### Most appropriate sub-area of Processing 4?

PDE

### Processing version

4.3.1

### Operating system

macOS 15.1.1

### Steps to reproduce this

1. Run a sketch

### snippet

```processing
circle(50, 50, 20);
```

### Additional context

The following output is displayed in the console when I run sketches on macOS Sequoia (15.x):

```
2024-12-01 16:46:52.952 java[13464:338806] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-01 16:46:52.952 java[13464:338806] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

These messages didn't appear with Processing 4.3.1 on macOS Sonoma (14.x). There might be some hints in this [discussion](https://discussions.apple.com/thread/255761734?sortBy=rank).

**Comment by SableRaf** [comment]
Thanks for raising this issue Nick! 

From reading the [discussion](https://discussions.apple.com/thread/255761734?sortBy=rank) you linked and [other reports](https://bugs.openjdk.org/browse/JDK-8340330) of [that same issue](https://github.com/zegervdv/homebrew-zathura/issues/129) popping up in other projects, it seems to be an issue with macOS Sequoia and its [InputMethodKit](https://developer.apple.com/documentation/inputmethodkit).

Here are some of the comments I found that seemed relevant:

> The log comes from a non-categorized `NSLog` in `+[IMKClient subclass]` and `+[IMKInputSession subclass]`, and whether `IMKClient_Modern` or `IMKClient_Legacy` is in use doesn't change whether the `NSLog` is called.
>
> It doesn’t seem to output when running via Xcode, presumably because Xcode filters it out in its oslog shim.

Source: https://github.com/zegervdv/homebrew-zathura/issues/129#issuecomment-2509729373

> The warning seems to have no impact on performance or security, and I would simply wait until a future update, and contact AppleINC.

Source: https://github.com/dotnet/maui/issues/24794#issuecomment-2443154660

Looks like something that only Apple can fix. Since it is not causing any other issues, maybe we can suppress the warnings somehow, if only to avoid confusing Processing users on macOS 15+? cc @Stefterv
